
version: 2
models:
  - name: stg_raw_saas_metrics_data
    description: "Staging model for raw SaaS metrics data."
    columns:
      - name: customer_id
        description: "The unique identifier for a customer."
        tests:
          - unique
          - not_null
      - name: subscription_start_date
        description: "The date the customer's subscription began."
        tests:
          - not_null
