
version: 2
sources:
  - name: raw
    description: "Raw data ingested from external sources."
    schema: public
    tables:
      - name: raw_saas_metrics
        description: "Raw financial metrics data ingested from a JSON file."
